# To use:
#
#   $ micromamba env create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate fe
#
name: fe
channels:
  - conda-forge
dependencies:
  - compilers
  - fpm
  - blas
  - gfortran
  - pkg-config
  - openblas
  - openmp
  - meson
  # Documentation
  - doxygen==1.9.1 # for doxyYoda
  - graphviz # for dot
